import { loadEnv } from '@/utilities/load-env'

loadEnv()

const { getPayload } = await import('payload')
const { default: config } = await import('@payload-config')

/**
 * Files photographs under the section they actually show.
 *
 * WHY THIS EXISTS SEPARATELY FROM `media.ts`
 * -----------------------------------------
 * `media.ts` sets `unit` and `category` for the photographs it uploads from
 * `assets/images`, and that covers most of the library. It does not cover
 * everything:
 *
 *   - photographs brought in through `npm run photos:import`, whose section
 *     came from a manifest row in `photos-inbox/` — a working folder that is
 *     deliberately not in version control, so nothing in the repository
 *     records what that row said;
 *   - photographs generated by another script, such as the portal's vision
 *     backdrop, which `vision-background.ts` creates and never files.
 *
 * A correction to either of those lives only in the database. That was fine
 * when the database was a developer's own; it is not fine now that the
 * database ships in `db/siws-content.sql.gz` and a teammate restores it. This
 * file is where such a correction is written down so it survives a rebuild.
 *
 * WHAT IT IS FOR, AND WHAT IT IS NOT FOR
 * --------------------------------------
 * It corrects the FILING of a photograph — which section's gallery it belongs
 * in — and, for a photograph no seed declares, its CAPTION. It touches neither
 * alt text nor consent records. If a photograph whose words a seed writes has
 * the wrong ones, they belong in that seed and not here; this is only for the
 * ones `photos:import` brought in, whose words exist nowhere but the database.
 *
 * Run with:  npm run seed:image-filing   (then seed:galleries, then seed:nav)
 */

const FILING: {
  filename: string
  unit: string
  category: string
  because: string
  /** Set false to keep a photograph out of the gallery wall while leaving the record for the pages that point at it. */
  showInGallery?: boolean
  /**
   * A caption for a photograph no seed uploads, whose words live only here.
   *
   * `null` CLEARS one. A photograph brought in through `photos:import` is
   * declared by no seed, so a caption on it can be corrected here and nowhere
   * else — and taking one off is as much a correction as rewriting it.
   *
   * CHECK THAT NO SEED OWNS IT FIRST, and check by stem rather than by the
   * name in the library. `media.ts` and `onam.ts` both match on the base name
   * — Payload appends `-1` to any name already taken on disk, and this
   * repository commits `media/`, so almost every row they own is stored under
   * a suffixed name. `kg-sports-day-winners-1.jpg` looks like a photograph no
   * seed declares and is in fact `kg-sports-day-winners.jpg` in `media.ts`.
   * Writing its caption here as well leaves two files disagreeing about one
   * photograph, with the winner decided by the order of `seed:refresh`.
   */
  caption?: string | null
}[] = [
  {
    filename: 'ignited-mind-lab-2026.jpg',
    unit: 'kindergarten',
    category: 'Achievements',
    because:
      'The eleven children are in the yellow-and-green Kindergarten uniform, and the certificates read "Class Sr. KG". It was filed under Primary, so it sat on the Primary wall and counted as a Primary photograph.',
  },
  {
    filename: 'kg-activity-table.jpg',
    unit: 'kindergarten',
    category: 'In the classroom',
    caption: null,
    because:
      'It was filed under "Classrooms" while every other Kindergarten classroom photograph is under "In the classroom", so the gallery grew two sections that mean the same thing — one of them holding a single tile. The category is set in no seed, which is why it survived a rebuild; this is where a photograph media.ts does not upload gets filed. The caption went with it: "Activity-based learning in the early years", under a heading that already reads "In the classroom", beside a second tile saying the same thing.',
  },
  {
    filename: 'primary-classroom.jpg',
    unit: 'primary',
    category: 'In the classroom',
    caption: null,
    because:
      'Filed under "Classrooms" while every other classroom photograph on the site is under "In the classroom" — the same fault as `kg-activity-table.jpg` above, and with the same result: a category of one, folded into "More photographs" at the foot of the wall instead of joining the eight pictures it belongs with. No seed declares this photograph, so the category could only be corrected here. Its caption is cleared for the same reason the others in that group are: "Learning in the Primary classroom" is the heading it sits under, said twice.',
  },
  {
    filename: 'portal-vision-background.jpg',
    unit: 'secondary',
    category: 'In the classroom',
    /*
     * NO `caption` HERE, deliberately, and this is the one row that must not
     * have one. `seed:vision-bg` runs AFTER this step and rewrites the words
     * on every run, so a caption set here is undone a moment later — which is
     * exactly what happened when this row carried `caption: null` and the
     * library came back captioned anyway. The words live in
     * `vision-background.ts`; the filing lives here.
     */
    because:
      '`vision-background.ts` generates this photograph and files it under no section at all, so without this row it belongs to nowhere and appears on no wall.',
  },
  /*
   * THE ONAM CELEBRATION, ON THE WALL ONCE INSTEAD OF TWICE (2026-09-02).
   *
   * Below are the duplicate copies, taken out of the gallery. The originals
   * stay: `onam.ts` maintains them, and its section is the one the Events page
   * links into by anchor.
   */
  {
    filename: 'onam-2026-assembly.jpg',
    unit: 'primary',
    category: 'Onam',
    showInGallery: false,
    // Cleared to agree with `siws-onam-assembly-2.jpg`, which is the same
    // photograph and is the copy on the wall. Both are on the Primary
    // section's "Photographs" band, and one picture cannot be captioned twice
    // over and differently.
    caption: null,
    because:
      'The same photograph is in the library twice — once here and once as `siws-onam-assembly-2.jpg`, byte for byte, from the one file in assets/images. Two seeds imported it under two names: `onam.ts`, which owns the set and builds the "Onam Event" section the Events card links to, and an earlier import that left these behind. So the Primary gallery carried the whole celebration twice, under "Onam" and again under "Onam Event". This copy comes off the wall rather than being deleted, because `primary.ts` still points at it for a page photograph.',
  },
  {
    filename: 'onam-2026-pookalam.jpg',
    unit: 'primary',
    category: 'Onam',
    showInGallery: false,
    caption: 'The Onam pookalam',
    because:
      'The same photograph is in the library twice — once here and once as `siws-onam-children-pookalam-2.jpg`, byte for byte, from the one file in assets/images. Two seeds imported it under two names: `onam.ts`, which owns the set and builds the "Onam Event" section the Events card links to, and an earlier import that left these behind. So the Primary gallery carried the whole celebration twice, under "Onam" and again under "Onam Event". This copy comes off the wall rather than being deleted, because `primary.ts` still points at it for a page photograph.',
  },
  {
    filename: 'onam-2026-lighting-the-lamp.jpg',
    unit: 'primary',
    category: 'Onam',
    showInGallery: false,
    caption: 'Lighting the lamp to open Onam',
    because:
      'The same photograph is in the library twice — once here and once as `siws-onam-lamp-lighting-2.jpg`, byte for byte, from the one file in assets/images. Two seeds imported it under two names: `onam.ts`, which owns the set and builds the "Onam Event" section the Events card links to, and an earlier import that left these behind. So the Primary gallery carried the whole celebration twice, under "Onam" and again under "Onam Event". This copy comes off the wall rather than being deleted, because `primary.ts` still points at it for a page photograph.',
  },
  {
    filename: 'onam-2026-teachers.jpg',
    unit: 'primary',
    category: 'Onam',
    showInGallery: false,
    caption: 'Our teaching team at Onam',
    because:
      'The same photograph is in the library twice — once here and once as `siws-onam-teachers-2.jpg`, byte for byte, from the one file in assets/images. Two seeds imported it under two names: `onam.ts`, which owns the set and builds the "Onam Event" section the Events card links to, and an earlier import that left these behind. So the Primary gallery carried the whole celebration twice, under "Onam" and again under "Onam Event". This copy comes off the wall rather than being deleted, because `primary.ts` still points at it for a page photograph.',
  },
  {
    filename: 'onam-2026-display-board.jpg',
    unit: 'primary',
    category: 'Onam',
    showInGallery: false,
    caption: 'The Ek Bharat Shreshtha Bharat display',
    because:
      'The same photograph is in the library twice — once here and once as `siws-onam-display-board-2.jpg`, byte for byte, from the one file in assets/images. Two seeds imported it under two names: `onam.ts`, which owns the set and builds the "Onam Event" section the Events card links to, and an earlier import that left these behind. So the Primary gallery carried the whole celebration twice, under "Onam" and again under "Onam Event". This copy comes off the wall rather than being deleted, because `primary.ts` still points at it for a page photograph.',
  },
]

const main = async () => {
  const payload = await getPayload({ config })

  const { docs: units } = await payload.find({
    collection: 'units',
    limit: 20,
    depth: 0,
    overrideAccess: true,
  })
  const unitId = new Map(units.map((u) => [String(u.slug), u.id]))

  let corrected = 0

  for (const entry of FILING) {
    const target = unitId.get(entry.unit)
    if (!target)
      throw new Error(`No unit with the slug "${entry.unit}" — run \`npm run seed\` first.`)

    const { docs } = await payload.find({
      collection: 'media',
      where: { filename: { equals: entry.filename } },
      limit: 1,
      depth: 0,
      overrideAccess: true,
    })

    const item = docs[0]
    if (!item) {
      payload.logger.warn(`Not in the library, so nothing to file: ${entry.filename}`)
      continue
    }

    const wall = entry.showInGallery ?? true
    /*
     * Three states, not two. A row with no `caption` leaves the words alone;
     * `null` clears them; a string replaces them. Reading an absent caption as
     * "clear it" would have wiped the words off every photograph this table
     * files for its section only.
     */
    const held = (item.caption as string | null) ?? null
    const caption = entry.caption === undefined ? held : entry.caption
    if (
      item.unit === target &&
      item.category === entry.category &&
      item.showInGallery === wall &&
      held === caption
    )
      continue

    await payload.update({
      collection: 'media',
      id: item.id,
      data: { unit: target, category: entry.category, showInGallery: wall, caption } as never,
      overrideAccess: true,
    })

    payload.logger.info(
      `Filed ${entry.filename} under ${entry.unit} / ${entry.category}. ${entry.because}`,
    )
    corrected += 1
  }

  payload.logger.info(
    corrected === 0
      ? 'Every photograph was already filed correctly.'
      : `${corrected} photograph(s) re-filed. Run npm run seed:galleries next, then npm run seed:nav.`,
  )

  /*
   * Anything with no section at all is reported rather than guessed at. A
   * photograph that belongs nowhere appears on no section's wall, which is a
   * silent way to lose one — and the fix is a line in the table above, written
   * by somebody who has looked at the picture.
   */
  const { docs: all } = await payload.find({
    collection: 'media',
    limit: 1000,
    depth: 0,
    overrideAccess: true,
    sort: 'filename',
  })

  const unfiled = all.filter((item) => !item.unit)
  if (unfiled.length > 0) {
    payload.logger.warn(
      `${unfiled.length} photograph(s) belong to no section and so appear on no gallery: ${unfiled
        .map((item) => item.filename)
        .join(', ')}. Look at each one and add it to FILING in src/seed/image-filing.ts.`,
    )
  }

  process.exit(0)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
