import { loadEnv } from '@/utilities/load-env'

loadEnv()

const { getPayload } = await import('payload')
const { default: config } = await import('@payload-config')

/**
 * Files photographs under the section they actually show.
 *
 * WHY THIS EXISTS SEPARATELY FROM `media.ts`
 * -----------------------------------------
 * `media.ts` sets `unit` and `category` for the photographs it uploads from
 * `assets/images`, and that covers most of the library. It does not cover
 * everything:
 *
 *   - photographs brought in through `npm run photos:import`, whose section
 *     came from a manifest row in `photos-inbox/` — a working folder that is
 *     deliberately not in version control, so nothing in the repository
 *     records what that row said;
 *   - photographs generated by another script, such as the portal's vision
 *     backdrop, which `vision-background.ts` creates and never files.
 *
 * A correction to either of those lives only in the database. That was fine
 * when the database was a developer's own; it is not fine now that the
 * database ships in `db/siws-content.sql.gz` and a teammate restores it. This
 * file is where such a correction is written down so it survives a rebuild.
 *
 * WHAT IT IS FOR, AND WHAT IT IS NOT FOR
 * --------------------------------------
 * It corrects the FILING of a photograph — which section's gallery it belongs
 * in. It does not touch alt text, captions, consent records or anything else.
 * If a photograph is in the wrong place, it goes here; if its words are wrong,
 * they belong in the seed that writes them.
 *
 * Run with:  npm run seed:image-filing   (then seed:galleries, then seed:nav)
 */

const FILING: {
  filename: string
  unit: string
  category: string
  because: string
  /** Set false to keep a photograph out of the gallery wall while leaving the record for the pages that point at it. */
  showInGallery?: boolean
  /** A caption for a photograph no seed uploads, whose words live only here. */
  caption?: string
}[] = [
  {
    filename: 'ignited-mind-lab-2026.jpg',
    unit: 'kindergarten',
    category: 'Achievements',
    because:
      'The eleven children are in the yellow-and-green Kindergarten uniform, and the certificates read "Class Sr. KG". It was filed under Primary, so it sat on the Primary wall and counted as a Primary photograph.',
  },
  {
    filename: 'kg-activity-table.jpg',
    unit: 'kindergarten',
    category: 'In the classroom',
    because:
      'It was filed under "Classrooms" while every other Kindergarten classroom photograph is under "In the classroom", so the gallery grew two sections that mean the same thing — one of them holding a single tile. The category is set in no seed, which is why it survived a rebuild; this is where a photograph media.ts does not upload gets filed.',
  },
  {
    filename: 'primary-classroom.jpg',
    unit: 'primary',
    category: 'In the classroom',
    caption: 'Learning in the Primary classroom',
    because:
      'Filed under "Classrooms" while every other classroom photograph on the site is under "In the classroom" — the same fault as `kg-activity-table.jpg` above, and with the same result: a category of one, folded into "More photographs" at the foot of the wall instead of joining the eight pictures it belongs with. No seed declares this photograph, so the category could only be corrected here.',
  },
  {
    filename: 'kg-activity-table.jpg',
    unit: 'kindergarten',
    category: 'In the classroom',
    caption: 'Activity-based learning in the early years',
    because:
      'The caption read "A Kindergarten class at the activity table." — a description of the photograph rather than of what the section does, and the only one left on the site written that way. `photos:import` brought this picture in, so no seed declares it and the words could only be corrected here.',
  },
  {
    filename: 'portal-vision-background.jpg',
    unit: 'secondary',
    category: 'In the classroom',
    caption: 'Collaboration and hands-on learning',
    because:
      'The caption was a sentence — "Fostering collaboration and hands-on learning every day." — where every other caption on the site is a label. `vision-background.ts` generates this picture and never captions it, so the words could only be corrected here.',
  },
  /*
   * THE ONAM CELEBRATION, ON THE WALL ONCE INSTEAD OF TWICE (2026-09-02).
   *
   * Below are the duplicate copies, taken out of the gallery. The originals
   * stay: `onam.ts` maintains them, and its section is the one the Events page
   * links into by anchor.
   */
  {
    filename: 'onam-2026-assembly.jpg',
    unit: 'primary',
    category: 'Onam',
    showInGallery: false,
    caption: 'Onam at the Primary Section',
    because:
      'The same photograph is in the library twice — once here and once as `siws-onam-assembly-2.jpg`, byte for byte, from the one file in assets/images. Two seeds imported it under two names: `onam.ts`, which owns the set and builds the "Onam Event" section the Events card links to, and an earlier import that left these behind. So the Primary gallery carried the whole celebration twice, under "Onam" and again under "Onam Event". This copy comes off the wall rather than being deleted, because `primary.ts` still points at it for a page photograph.',
  },
  {
    filename: 'onam-2026-pookalam.jpg',
    unit: 'primary',
    category: 'Onam',
    showInGallery: false,
    caption: 'The Onam pookalam',
    because:
      'The same photograph is in the library twice — once here and once as `siws-onam-children-pookalam-2.jpg`, byte for byte, from the one file in assets/images. Two seeds imported it under two names: `onam.ts`, which owns the set and builds the "Onam Event" section the Events card links to, and an earlier import that left these behind. So the Primary gallery carried the whole celebration twice, under "Onam" and again under "Onam Event". This copy comes off the wall rather than being deleted, because `primary.ts` still points at it for a page photograph.',
  },
  {
    filename: 'onam-2026-lighting-the-lamp.jpg',
    unit: 'primary',
    category: 'Onam',
    showInGallery: false,
    caption: 'Lighting the lamp to open Onam',
    because:
      'The same photograph is in the library twice — once here and once as `siws-onam-lamp-lighting-2.jpg`, byte for byte, from the one file in assets/images. Two seeds imported it under two names: `onam.ts`, which owns the set and builds the "Onam Event" section the Events card links to, and an earlier import that left these behind. So the Primary gallery carried the whole celebration twice, under "Onam" and again under "Onam Event". This copy comes off the wall rather than being deleted, because `primary.ts` still points at it for a page photograph.',
  },
  {
    filename: 'onam-2026-teachers.jpg',
    unit: 'primary',
    category: 'Onam',
    showInGallery: false,
    caption: 'Our teaching team at Onam',
    because:
      'The same photograph is in the library twice — once here and once as `siws-onam-teachers-2.jpg`, byte for byte, from the one file in assets/images. Two seeds imported it under two names: `onam.ts`, which owns the set and builds the "Onam Event" section the Events card links to, and an earlier import that left these behind. So the Primary gallery carried the whole celebration twice, under "Onam" and again under "Onam Event". This copy comes off the wall rather than being deleted, because `primary.ts` still points at it for a page photograph.',
  },
  {
    filename: 'onam-2026-display-board.jpg',
    unit: 'primary',
    category: 'Onam',
    showInGallery: false,
    caption: 'The Ek Bharat Shreshtha Bharat display',
    because:
      'The same photograph is in the library twice — once here and once as `siws-onam-display-board-2.jpg`, byte for byte, from the one file in assets/images. Two seeds imported it under two names: `onam.ts`, which owns the set and builds the "Onam Event" section the Events card links to, and an earlier import that left these behind. So the Primary gallery carried the whole celebration twice, under "Onam" and again under "Onam Event". This copy comes off the wall rather than being deleted, because `primary.ts` still points at it for a page photograph.',
  },
]

const main = async () => {
  const payload = await getPayload({ config })

  const { docs: units } = await payload.find({
    collection: 'units',
    limit: 20,
    depth: 0,
    overrideAccess: true,
  })
  const unitId = new Map(units.map((u) => [String(u.slug), u.id]))

  let corrected = 0

  for (const entry of FILING) {
    const target = unitId.get(entry.unit)
    if (!target)
      throw new Error(`No unit with the slug "${entry.unit}" — run \`npm run seed\` first.`)

    const { docs } = await payload.find({
      collection: 'media',
      where: { filename: { equals: entry.filename } },
      limit: 1,
      depth: 0,
      overrideAccess: true,
    })

    const item = docs[0]
    if (!item) {
      payload.logger.warn(`Not in the library, so nothing to file: ${entry.filename}`)
      continue
    }

    const wall = entry.showInGallery ?? true
    const caption = entry.caption ?? (item.caption as string | undefined)
    if (
      item.unit === target &&
      item.category === entry.category &&
      item.showInGallery === wall &&
      item.caption === caption
    )
      continue

    await payload.update({
      collection: 'media',
      id: item.id,
      data: { unit: target, category: entry.category, showInGallery: wall, caption } as never,
      overrideAccess: true,
    })

    payload.logger.info(
      `Filed ${entry.filename} under ${entry.unit} / ${entry.category}. ${entry.because}`,
    )
    corrected += 1
  }

  payload.logger.info(
    corrected === 0
      ? 'Every photograph was already filed correctly.'
      : `${corrected} photograph(s) re-filed. Run npm run seed:galleries next, then npm run seed:nav.`,
  )

  /*
   * Anything with no section at all is reported rather than guessed at. A
   * photograph that belongs nowhere appears on no section's wall, which is a
   * silent way to lose one — and the fix is a line in the table above, written
   * by somebody who has looked at the picture.
   */
  const { docs: all } = await payload.find({
    collection: 'media',
    limit: 1000,
    depth: 0,
    overrideAccess: true,
    sort: 'filename',
  })

  const unfiled = all.filter((item) => !item.unit)
  if (unfiled.length > 0) {
    payload.logger.warn(
      `${unfiled.length} photograph(s) belong to no section and so appear on no gallery: ${unfiled
        .map((item) => item.filename)
        .join(', ')}. Look at each one and add it to FILING in src/seed/image-filing.ts.`,
    )
  }

  process.exit(0)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
