import { loadEnv } from '@/utilities/load-env'

loadEnv()

const { getPayload } = await import('payload')
const { default: config } = await import('@payload-config')

/**
 * Files photographs under the section they actually show.
 *
 * WHY THIS EXISTS SEPARATELY FROM `media.ts`
 * -----------------------------------------
 * `media.ts` sets `unit` and `category` for the photographs it uploads from
 * `assets/images`, and that covers most of the library. It does not cover
 * everything:
 *
 *   - photographs brought in through `npm run photos:import`, whose section
 *     came from a manifest row in `photos-inbox/` — a working folder that is
 *     deliberately not in version control, so nothing in the repository
 *     records what that row said;
 *   - photographs generated by another script, such as the portal's vision
 *     backdrop, which `vision-background.ts` creates and never files.
 *
 * A correction to either of those lives only in the database. That was fine
 * when the database was a developer's own; it is not fine now that the
 * database ships in `db/siws-content.sql.gz` and a teammate restores it. This
 * file is where such a correction is written down so it survives a rebuild.
 *
 * WHAT IT IS FOR, AND WHAT IT IS NOT FOR
 * --------------------------------------
 * It corrects the FILING of a photograph — which section's gallery it belongs
 * in. It does not touch alt text, captions, consent records or anything else.
 * If a photograph is in the wrong place, it goes here; if its words are wrong,
 * they belong in the seed that writes them.
 *
 * Run with:  npm run seed:image-filing   (then seed:galleries, then seed:nav)
 */

const FILING: { filename: string; unit: string; category: string; because: string }[] = [
  {
    filename: 'ignited-mind-lab-2026.jpg',
    unit: 'kindergarten',
    category: 'Achievements',
    because:
      'The eleven children are in the yellow-and-green Kindergarten uniform, and the certificates read "Class Sr. KG". It was filed under Primary, so it sat on the Primary wall and counted as a Primary photograph.',
  },
  {
    filename: 'portal-vision-background.jpg',
    unit: 'secondary',
    category: 'In the classroom',
    because:
      'Secondary students in house-colour shirts making tricolour decorations in the science laboratory. It is generated by vision-background.ts for the portal and was never filed at all, so it belonged to no section and appeared on no wall.',
  },
]

const main = async () => {
  const payload = await getPayload({ config })

  const { docs: units } = await payload.find({
    collection: 'units',
    limit: 20,
    depth: 0,
    overrideAccess: true,
  })
  const unitId = new Map(units.map((u) => [String(u.slug), u.id]))

  let corrected = 0

  for (const entry of FILING) {
    const target = unitId.get(entry.unit)
    if (!target)
      throw new Error(`No unit with the slug "${entry.unit}" — run \`npm run seed\` first.`)

    const { docs } = await payload.find({
      collection: 'media',
      where: { filename: { equals: entry.filename } },
      limit: 1,
      depth: 0,
      overrideAccess: true,
    })

    const item = docs[0]
    if (!item) {
      payload.logger.warn(`Not in the library, so nothing to file: ${entry.filename}`)
      continue
    }

    if (item.unit === target && item.category === entry.category) continue

    await payload.update({
      collection: 'media',
      id: item.id,
      data: { unit: target, category: entry.category } as never,
      overrideAccess: true,
    })

    payload.logger.info(
      `Filed ${entry.filename} under ${entry.unit} / ${entry.category}. ${entry.because}`,
    )
    corrected += 1
  }

  payload.logger.info(
    corrected === 0
      ? 'Every photograph was already filed correctly.'
      : `${corrected} photograph(s) re-filed. Run npm run seed:galleries next, then npm run seed:nav.`,
  )

  /*
   * Anything with no section at all is reported rather than guessed at. A
   * photograph that belongs nowhere appears on no section's wall, which is a
   * silent way to lose one — and the fix is a line in the table above, written
   * by somebody who has looked at the picture.
   */
  const { docs: all } = await payload.find({
    collection: 'media',
    limit: 1000,
    depth: 0,
    overrideAccess: true,
    sort: 'filename',
  })

  const unfiled = all.filter((item) => !item.unit)
  if (unfiled.length > 0) {
    payload.logger.warn(
      `${unfiled.length} photograph(s) belong to no section and so appear on no gallery: ${unfiled
        .map((item) => item.filename)
        .join(', ')}. Look at each one and add it to FILING in src/seed/image-filing.ts.`,
    )
  }

  process.exit(0)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
